services:
  rhizome:
    image: ghcr.io/cstanze/rhizome:latest
    container_name: rhizome
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
    environment:
      - TZ=UTC